# Generated by Django 2.2.3 on 2019-11-17 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 17, 21, 15, 12, 481017)),
        ),
    ]
